export const ADMIN_ROUTE = '/admin'
export const LOGIN_ROUTE = '/login'
export const REGISTRATION_ROUTE = '/registration'
export const INDEX_ROUTE = '/'
export const TICKETS_ROUTE = '/tickets'
export const CITIES_ROUTE = '/cities'
export const TRAINS_ROUTE = '/trains'
export const ROUTES_ROUTE = '/routes'